services:
  python_server:
    build: .
    container_name: python_server
    environment:
      - PORT=${PORT:-9090}
    ports:
      - "${PORT:-9090}:${PORT:-9090}"
    command: >
      "${PORT:-9090}"
    restart: unless-stopped
